### ISSUE TITLE
Variable syntax isn't converted

### ISSUE THREAD

**Issue by ooker777** [nyabkun/bash-to-powershell-converter#1]
`x=string` in bash should be converted to `$x='string'` in PowerShell, but it doesn't

**Comment by nyabkun** [comment]
Thank you for your post.

The string will be converted if you enclose it in single quotes.

This script is very simple, as you can see from the code, and just uses regular expressions to replace strings.

It does not support detailed variable interpolation, so it is not designed to convert strings without quotes, where mistakes may occur.

I hope you will rewrite and use it according to the script you want to convert.
Again, it's a very simple conversion script.
